SELECT 'ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN ' || column_name || ';' AS drop_stmt
FROM user_tab_columns
WHERE table_name = 'UFS_CITIZEN_DATA'
  AND (UPPER(column_name) LIKE '%AADHAAR%'
       OR UPPER(column_name) LIKE '%MOBILE%'
       OR UPPER(column_name) LIKE '%INCOME%');
       
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN MOBILE_NUMBER;
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN SOURCE_OF_INCOME;
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN AVG_MONTHLY_INCOME;
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN AADHAAR_NUMBER;
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN FATHER_HUSBAND_AADHAAR;
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN DEDICATED_MOBILE_STATUS;
ALTER TABLE UFS_CITIZEN_DATA DROP COLUMN HUSBAND_AADHAAR;